name: flutter_crypto_security
description: "A new Flutter package to deal with encryption and decryption of data."
version: 0.0.1
publish_to: none
homepage: "https://github.com/sudhi001/flutter_crypto_security"  # Add the URL of your package homepage, like a GitHub repo.

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^3.9.1
  encrypt: ^5.0.3
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

