import 'dart:convert';
import 'dart:typed_data';

import 'package:pointycastle/export.dart';

import 'der.dart';

const String _rsaEncryptionOid = '1.2.840.113549.1.1.1';

/// [RSAPrivateKey] that keeps the public exponent stored in the key file.
///
/// PointyCastle derives `e = d⁻¹ mod φ(n)`; keys generated by Go/OpenSSL use
/// `d = e⁻¹ mod λ(n)`, for which that derivation yields a different (huge)
/// value. Keeping the original exponent makes re-encoding byte-identical.
class _ParsedRsaPrivateKey extends RSAPrivateKey {
  final BigInt _publicExponent;

  _ParsedRsaPrivateKey(
    super.modulus,
    super.privateExponent,
    BigInt super.p,
    BigInt super.q,
    this._publicExponent,
  );

  @override
  BigInt? get publicExponent => _publicExponent;
}

/// PEM/DER (de)serialisation of RSA keys in the formats shared with the Go
/// `crypto_utils` package and the Rust crate:
///
/// * private keys: PKCS#1 `RSA PRIVATE KEY` (PKCS#8 `PRIVATE KEY` also parses)
/// * public keys:  PKIX `PUBLIC KEY` (PKCS#1 `RSA PUBLIC KEY` also parses)
class RsaKeyCodec {
  RsaKeyCodec._();

  // ------------------------------------------------------------------ parse

  /// Parses a PEM string into an [RSAPrivateKey].
  static RSAPrivateKey parsePrivateKeyPem(String pem) {
    final (label, der) = _decodePem(pem);
    switch (label) {
      case 'RSA PRIVATE KEY':
        return _parsePkcs1PrivateKey(der);
      case 'PRIVATE KEY':
        return _parsePkcs8PrivateKey(der);
      default:
        throw ArgumentError('Unsupported private key PEM label "$label"');
    }
  }

  /// Parses a PEM string into an [RSAPublicKey].
  static RSAPublicKey parsePublicKeyPem(String pem) {
    final (label, der) = _decodePem(pem);
    switch (label) {
      case 'PUBLIC KEY':
        return _parsePkixPublicKey(der);
      case 'RSA PUBLIC KEY':
        return _parsePkcs1PublicKey(der);
      default:
        throw ArgumentError('Unsupported public key PEM label "$label"');
    }
  }

  /// Parses a base64(PEM) string into an [RSAPrivateKey].
  static RSAPrivateKey parsePrivateKeyBase64(String base64Pem) =>
      parsePrivateKeyPem(_base64ToPem(base64Pem));

  /// Parses a base64(PEM) string into an [RSAPublicKey].
  static RSAPublicKey parsePublicKeyBase64(String base64Pem) =>
      parsePublicKeyPem(_base64ToPem(base64Pem));

  // ----------------------------------------------------------------- encode

  /// Encodes a private key as a PKCS#1 `RSA PRIVATE KEY` PEM string.
  static String encodePrivateKeyPem(RSAPrivateKey key) =>
      _encodePem('RSA PRIVATE KEY', encodePkcs1PrivateKey(key));

  /// Encodes a public key as a PKIX `PUBLIC KEY` PEM string.
  static String encodePublicKeyPem(RSAPublicKey key) =>
      _encodePem('PUBLIC KEY', encodePkixPublicKey(key));

  /// Encodes a private key as base64(PKCS#1 PEM).
  static String encodePrivateKeyBase64(RSAPrivateKey key) =>
      base64Encode(utf8.encode(encodePrivateKeyPem(key)));

  /// Encodes a public key as base64(PKIX PEM).
  static String encodePublicKeyBase64(RSAPublicKey key) =>
      base64Encode(utf8.encode(encodePublicKeyPem(key)));

  /// DER encoding of `RSAPrivateKey ::= SEQUENCE { 0, n, e, d, p, q, dP, dQ, qInv }`.
  static Uint8List encodePkcs1PrivateKey(RSAPrivateKey key) {
    final n = key.modulus!;
    final e = key.publicExponent!;
    final d = key.privateExponent!;
    final p = key.p!;
    final q = key.q!;
    final one = BigInt.one;
    return DerWriter.sequence([
      DerWriter.integer(BigInt.zero),
      DerWriter.integer(n),
      DerWriter.integer(e),
      DerWriter.integer(d),
      DerWriter.integer(p),
      DerWriter.integer(q),
      DerWriter.integer(d % (p - one)),
      DerWriter.integer(d % (q - one)),
      DerWriter.integer(q.modInverse(p)),
    ]);
  }

  /// DER encoding of `SubjectPublicKeyInfo` for an RSA key.
  static Uint8List encodePkixPublicKey(RSAPublicKey key) {
    final rsaPublicKey = DerWriter.sequence([
      DerWriter.integer(key.modulus!),
      DerWriter.integer(key.publicExponent!),
    ]);
    return DerWriter.sequence([
      DerWriter.sequence([
        DerWriter.oid(_rsaEncryptionOid),
        DerWriter.nullValue(),
      ]),
      DerWriter.bitString(rsaPublicKey),
    ]);
  }

  // --------------------------------------------------------------- internal

  static RSAPrivateKey _parsePkcs1PrivateKey(Uint8List der) {
    final seq = DerReader(der).next();
    final f = seq.children;
    if (f.length < 6) {
      throw const FormatException('Invalid PKCS#1 RSAPrivateKey');
    }
    return _ParsedRsaPrivateKey(
      f[1].bigInt,
      f[3].bigInt,
      f[4].bigInt,
      f[5].bigInt,
      f[2].bigInt,
    );
  }

  static RSAPrivateKey _parsePkcs8PrivateKey(Uint8List der) {
    final f = DerReader(der).next().children;
    if (f.length < 3) {
      throw const FormatException('Invalid PKCS#8 PrivateKeyInfo');
    }
    _requireRsaAlgorithm(f[1]);
    if (f[2].tag != DerTag.octetString) {
      throw const FormatException('Invalid PKCS#8 PrivateKeyInfo');
    }
    return _parsePkcs1PrivateKey(f[2].value);
  }

  static RSAPublicKey _parsePkixPublicKey(Uint8List der) {
    final f = DerReader(der).next().children;
    if (f.length < 2) {
      throw const FormatException('Invalid SubjectPublicKeyInfo');
    }
    _requireRsaAlgorithm(f[0]);
    return _parsePkcs1PublicKey(f[1].bitStringBytes);
  }

  static RSAPublicKey _parsePkcs1PublicKey(Uint8List der) {
    final f = DerReader(der).next().children;
    if (f.length < 2) {
      throw const FormatException('Invalid PKCS#1 RSAPublicKey');
    }
    return RSAPublicKey(f[0].bigInt, f[1].bigInt);
  }

  static void _requireRsaAlgorithm(DerElement algorithmIdentifier) {
    final parts = algorithmIdentifier.children;
    if (parts.isEmpty || parts[0].oidString != _rsaEncryptionOid) {
      throw const FormatException('Key algorithm is not rsaEncryption');
    }
  }

  static String _base64ToPem(String base64Pem) {
    try {
      return utf8.decode(base64Decode(base64Pem.trim()));
    } on FormatException catch (e) {
      throw ArgumentError('Key is not valid base64: ${e.message}');
    }
  }

  static (String, Uint8List) _decodePem(String pem) {
    final match = RegExp(
      r'-----BEGIN ([A-Z0-9 ]+)-----([\s\S]*?)-----END \1-----',
    ).firstMatch(pem);
    if (match == null) {
      throw ArgumentError('Input does not contain a PEM block');
    }
    final label = match.group(1)!;
    final body = match.group(2)!.replaceAll(RegExp(r'\s'), '');
    try {
      return (label, base64Decode(body));
    } on FormatException catch (e) {
      throw ArgumentError('PEM body is not valid base64: ${e.message}');
    }
  }

  static String _encodePem(String label, Uint8List der) {
    final b64 = base64Encode(der);
    final sb = StringBuffer('-----BEGIN $label-----\n');
    for (var i = 0; i < b64.length; i += 64) {
      sb.writeln(b64.substring(i, i + 64 > b64.length ? b64.length : i + 64));
    }
    sb.write('-----END $label-----\n');
    return sb.toString();
  }
}
